services:
  - type: web
    name: ai-resume-analyzer-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: pFHPNqLaIHlQSPgyPoLDhFSypBIXYeZO
      - key: JWT_SECRET
        value: mySecretKeyForResumeAnalyzerApp2024VeryLong!
      - key: GEMINI_API_KEY
        value: none
      - key: CORS_ORIGINS
        value: http://localhost:3001
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC